import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Header } from "@/components/common/header/header";
import { Footer } from "@/components/common/footer";
import CssBaseline from '@mui/material/CssBaseline';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
    <html lang="ja">
      <body className={inter.className} style={{"backgroundColor": "#E0E2EC"}}>
        <CssBaseline />
        <Header />
        {children}
        <Footer />
      </body>
    </html>
    </>
  );
}
