# Choose whatever you want, version >= 1.16
FROM golang:1.21-alpine

WORKDIR /app

RUN go install github.com/cosmtrek/air@latest

COPY ./api/go.mod ./api/go.sum ./
RUN go mod download

CMD ["air", "-c", ".air.toml", "--", "--env local"]